version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
